/// Comprehensive Tribal Lexicon Dataset for Jharkhand Primary Education (PALASH MTB-MLE)
/// Covers: Santhali (Ol Chiki + Devanagari), Ho (Devanagari), and Mundari (Devanagari)
class TribalLexiconData {
  // -------------------------------------------------------------
  // 1. Classroom Dialogue & Pedagogical Commands (Bidirectional)
  // -------------------------------------------------------------
  static final List<Map<String, dynamic>> classroomPhrases = [
    {
      'id': 'cp_greet',
      'intent': 'GREETING',
      'hindi': 'नमस्ते बच्चों',
      'keywords_hi': ['नमस्ते', 'प्रणाम', 'नमस्कार', 'हेलो', 'सुप्रभात'],
      'santhali': 'ᱡᱚᱦᱟᱨ ᱜᱤᱫᱽᱨᱟᱹ',
      'santhali_dev': 'जोहार गिद्रा',
      'santhali_latin': 'Johar gidra',
      'ho': 'जोहार होनको',
      'ho_latin': 'Johar honko',
      'mundari': 'जोहार हुनको',
      'mundari_latin': 'Johar hunko',
      'meaning_en': 'Hello / Greetings children',
    },
    {
      'id': 'cp_how_are_you',
      'intent': 'HOW_ARE_YOU',
      'hindi': 'आप सब कैसे हैं?',
      'keywords_hi': ['कैसे हो', 'कैसे हैं', 'कैसा है', 'सब ठीक'],
      'santhali': 'ᱟᱯᱮ ᱪᱮᱫ ᱞᱮᱠᱟ ᱢᱮᱱᱟᱜ ᱯᱮᱭᱟ?',
      'santhali_dev': 'आपे चेद लेका मेनाग पेया?',
      'santhali_latin': 'Ape ched leka menag peya?',
      'ho': 'अपे चिलके मेनापेया?',
      'ho_latin': 'Ape chilke menapeya?',
      'mundari': 'अपे चिलकेना मेनापेया?',
      'mundari_latin': 'Ape chilkena menapeya?',
      'meaning_en': 'How are you all?',
    },
    {
      'id': 'cp_we_are_fine',
      'intent': 'WE_ARE_FINE',
      'hindi': 'हम सब अच्छे हैं',
      'keywords_hi': ['अच्छे हैं', 'ठीक हैं', 'बढ़िया हैं', 'ठीकठाक'],
      'santhali': 'ᱟᱞᱮ ᱵᱮᱥ ᱜᱮ ᱢᱮᱱᱟᱜ ᱞᱮᱭᱟ',
      'santhali_dev': 'आले बेस गे मेनाग लेया',
      'santhali_latin': 'Ale bes ge menag leya',
      'ho': 'अले बेस मेनालेया',
      'ho_latin': 'Ale bes menaleya',
      'mundari': 'अले बुगिन मेनालेया',
      'mundari_latin': 'Ale bugin menaleya',
      'meaning_en': 'We are all good/fine',
    },
    {
      'id': 'cp_open_book',
      'intent': 'OPEN_BOOK',
      'hindi': 'अपनी किताब खोलो',
      'keywords_hi': ['किताब खोलो', 'पुस्तक खोलो', 'पन्ना खोलो'],
      'santhali': 'ᱟᱢᱟᱜ ᱯᱩᱛᱷᱤ ᱠᱷᱩᱞᱟᱹᱭ ᱢᱮ',
      'santhali_dev': 'आमाग पुथि खुलाय मे',
      'santhali_latin': 'Amag puthi khulae me',
      'ho': 'अमाः पुथि कुलै मे',
      'ho_latin': 'Amah puthi kulae me',
      'mundari': 'अमाः पुथी कुलै मे',
      'mundari_latin': 'Amah puthi kulae me',
      'meaning_en': 'Open your book',
    },
    {
      'id': 'cp_look_here',
      'intent': 'LOOK_HERE',
      'hindi': 'यहाँ देखो',
      'keywords_hi': ['यहाँ देखो', 'इधर देखो', 'बोर्ड पर देखो'],
      'santhali': 'ᱱᱚᱸᱰᱮ ᱧᱮᱞ ᱢᱮ',
      'santhali_dev': 'नोंडे ञेल मे',
      'santhali_latin': 'Nonde nyel me',
      'ho': 'नेनपा नेल मे',
      'ho_latin': 'Nenpa nel me',
      'mundari': 'नेते नेल मे',
      'mundari_latin': 'Nete nel me',
      'meaning_en': 'Look here / Look at the board',
    },
    {
      'id': 'cp_listen',
      'intent': 'LISTEN',
      'hindi': 'ध्यान से सुनो',
      'keywords_hi': ['ध्यान से सुनो', 'सुनो', 'मेरी बात सुनो'],
      'santhali': 'ᱫᱷᱮᱭᱟᱱ ᱛᱮ ᱟᱧᱡᱚᱢ ᱢᱮ',
      'santhali_dev': 'धेयान ते आंजोम मे',
      'santhali_latin': 'Dheyan te anjom me',
      'ho': 'मन लगाके आयुम मे',
      'ho_latin': 'Man lagake ayum me',
      'mundari': 'सुपुई ते आयुम मे',
      'mundari_latin': 'Supui te ayum me',
      'meaning_en': 'Listen carefully',
    },
    {
      'id': 'cp_repeat',
      'intent': 'REPEAT',
      'hindi': 'मेरे बाद दोहराओ',
      'keywords_hi': ['दोहराओ', 'मेरे बाद बोलो', 'पीछे बोलो'],
      'santhali': 'ᱤᱧ ᱛᱟᱭᱚᱢ ᱨᱚᱲ ᱢᱮ',
      'santhali_dev': 'इञ तायोम रोड़ मे',
      'santhali_latin': 'Iny tayom rod me',
      'ho': 'अयिंग तायोम काजि मे',
      'ho_latin': 'Aying tayom kaji me',
      'mundari': 'अयिंग तायोम जगर मे',
      'mundari_latin': 'Aying tayom jagar me',
      'meaning_en': 'Repeat after me',
    },
    {
      'id': 'cp_count_together',
      'intent': 'COUNT',
      'hindi': 'एक साथ गिनो',
      'keywords_hi': ['गिनो', 'गिनती करो', 'संख्या गिनो', 'साथ गिनो'],
      'santhali': 'ᱢᱤᱫ ᱥᱟᱶᱛᱮ ᱞᱮᱠᱷᱟᱭ ᱯᱮ',
      'santhali_dev': 'मिद सावते लेखाय पे',
      'santhali_latin': 'Mid sawte lekhay pe',
      'ho': 'मियद सांवते लेकाए पे',
      'ho_latin': 'Miyad sawte lekae pe',
      'mundari': 'मियद सोंगे लेकाए पे',
      'mundari_latin': 'Miyad songe lekae pe',
      'meaning_en': 'Count together',
    },
    {
      'id': 'cp_stand_up',
      'intent': 'STAND_UP',
      'hindi': 'खड़े हो जाओ',
      'keywords_hi': ['खड़े हो जाओ', 'खड़ा हो', 'उठो'],
      'santhali': 'ᱛᱤᱸᱜᱩᱱ ᱢᱮ',
      'santhali_dev': 'तिंगुन मे',
      'santhali_latin': 'Tingun me',
      'ho': 'तिंगुन मे',
      'ho_latin': 'Tingun me',
      'mundari': 'तिंगुन मे',
      'mundari_latin': 'Tingun me',
      'meaning_en': 'Stand up',
    },
    {
      'id': 'cp_sit_down',
      'intent': 'SIT_DOWN',
      'hindi': 'बैठ जाओ',
      'keywords_hi': ['बैठ जाओ', 'बैठो', 'अपनी जगह बैठो'],
      'santhali': 'ᱫᱩᱲᱩᱵ ᱢᱮ',
      'santhali_dev': 'दुड़ुब मे',
      'santhali_latin': 'Durup me',
      'ho': 'दुब मे',
      'ho_latin': 'Dub me',
      'mundari': 'दुब मे',
      'mundari_latin': 'Dub me',
      'meaning_en': 'Sit down',
    },
    {
      'id': 'cp_good_job',
      'intent': 'GOOD',
      'hindi': 'बहुत अच्छा',
      'keywords_hi': ['बहुत अच्छा', 'शाबाश', 'उत्कृष्ट', 'बहुत बढ़िया'],
      'santhali': 'ᱟᱹᱰᱤ ᱱᱟᱯᱟᱭ',
      'santhali_dev': 'आडि नापाय',
      'santhali_latin': 'Adi napay',
      'ho': 'एतोगान बेस',
      'ho_latin': 'Etogan bes',
      'mundari': 'पुरः बुगिन',
      'mundari_latin': 'Purah bugin',
      'meaning_en': 'Very good / Well done',
    },
    {
      'id': 'cp_try_again',
      'intent': 'TRY_AGAIN',
      'hindi': 'फिर से कोशिश करो',
      'keywords_hi': ['फिर से कोशिश करो', 'दोबारा करो', 'एक बार और'],
      'santhali': 'ᱟᱨᱦᱚᱸ ᱠᱩᱨᱩᱢᱩᱴᱩᱭ ᱢᱮ',
      'santhali_dev': 'आरहों कुरुमुटुय मे',
      'santhali_latin': 'Arho kurumutu me',
      'ho': 'आरहो कुरुमुटू मे',
      'ho_latin': 'Arho kurumutu me',
      'mundari': 'आरहो चेष्टाए मे',
      'mundari_latin': 'Arho chestae me',
      'meaning_en': 'Try again',
    },
    {
      'id': 'cp_write_slate',
      'intent': 'WRITE',
      'hindi': 'अपनी स्लेट पर लिखो',
      'keywords_hi': ['लिखो', 'स्लेट पर लिखो', 'कॉपी में लिखो', 'लिखिए'],
      'santhali': 'ᱟᱢᱟᱜ ᱥᱞᱮᱴ ᱨᱮ ᱚᱞ ᱢᱮ',
      'santhali_dev': 'आमाग स्लेट रे ओल मे',
      'santhali_latin': 'Amag slate re ol me',
      'ho': 'अमाः स्लेट रे ओल मे',
      'ho_latin': 'Amah slate re ol me',
      'mundari': 'अमाः स्लेट रे ओल मे',
      'mundari_latin': 'Amah slate re ol me',
      'meaning_en': 'Write on your slate',
    },
    {
      'id': 'cp_clap',
      'intent': 'CLAP',
      'hindi': 'सब बच्चे ताली बजाओ',
      'keywords_hi': ['ताली बजाओ', 'ताली मारो', 'ताली'],
      'santhali': 'ᱡᱚᱛᱚ ᱜᱤᱫᱽᱨᱟᱹ ᱛᱷᱟᱹᱭᱟᱹ ᱢᱮ',
      'santhali_dev': 'जोतो गिद्रा थाय मे',
      'santhali_latin': 'Joto gidra thaye me',
      'ho': 'सोबेन होनको ताली दुर मे',
      'ho_latin': 'Soben honko tali dur me',
      'mundari': 'सोबेन हुनको थाली साडी मे',
      'mundari_latin': 'Soben hunko thali sadi me',
      'meaning_en': 'All children clap hands',
    },
    {
      'id': 'cp_water',
      'intent': 'DRINK_WATER',
      'hindi': 'पानी पी लो',
      'keywords_hi': ['पानी पी लो', 'पानी पियो', 'पानी पीना', 'पानी चाहिए', 'पानी पीना है'],
      'santhali': 'ᱫᱟᱜ ᱧᱩᱭ ᱢᱮ',
      'santhali_dev': 'दाग ञुय मे',
      'santhali_latin': 'Dag nyuy me',
      'ho': 'दाः नुई मे',
      'ho_latin': 'Dah nui me',
      'mundari': 'दाः नुई मे',
      'mundari_latin': 'Dah nui me',
      'meaning_en': 'Drink water / Stay hydrated',
    },
    {
      'id': 'cp_quiet',
      'intent': 'BE_QUIET',
      'hindi': 'सब शांत हो जाओ',
      'keywords_hi': ['शांत हो जाओ', 'चुप रहो', 'शोर मत करो', 'शांति', 'चुप'],
      'santhali': 'ᱡᱚᱛᱚ ᱦᱚᱲ ᱛᱷᱤᱨ ᱠᱚᱜ ᱯᱮ',
      'santhali_dev': 'जोतो होड़ थीर कोग पे',
      'santhali_latin': 'Joto hor thir kog pe',
      'ho': 'सोबेन होड़ थीर लेन पे',
      'ho_latin': 'Soben hor thir len pe',
      'mundari': 'सोबेन होड़ थीर लेन पे',
      'mundari_latin': 'Soben hor thir len pe',
      'meaning_en': 'Everyone please be quiet',
    },
    {
      'id': 'cp_wash_hands',
      'intent': 'WASH_HANDS',
      'hindi': 'हाथ धो लो',
      'keywords_hi': ['हाथ धो लो', 'हाथ धो', 'हाथ साफ़ करो'],
      'santhali': 'ᱛᱤ ᱟᱹᱨᱩᱵ ᱢᱮ',
      'santhali_dev': 'ती आरुब मे',
      'santhali_latin': 'Ti arub me',
      'ho': 'ती अरुब मे',
      'ho_latin': 'Ti arub me',
      'mundari': 'ती अरुब मे',
      'mundari_latin': 'Ti arub me',
      'meaning_en': 'Wash your hands',
    },
    {
      'id': 'cp_play_game',
      'intent': 'PLAY_GAME',
      'hindi': 'चलो खेल खेलते हैं',
      'keywords_hi': ['खेल खेलते हैं', 'खेल खेलें', 'चलो खेलें', 'खेल खेलो'],
      'santhali': 'ᱫᱮᱞᱟ ᱵᱚᱱ ᱮᱱᱮᱡᱼᱟ',
      'santhali_dev': 'देला बोन एनेजा',
      'santhali_latin': 'Dela bon eneja',
      'ho': 'दिलाबों ईनीजा',
      'ho_latin': 'Dilabon inija',
      'mundari': 'दिलाबों ईनीजा',
      'mundari_latin': 'Dilabon inija',
      'meaning_en': 'Let us play a game together',
    },
    {
      'id': 'cp_sing',
      'intent': 'SING',
      'hindi': 'कविता / गाना गाओ',
      'keywords_hi': ['गाना गाओ', 'कविता गाओ', 'गाओ', 'कविता बोलो'],
      'santhali': 'ᱥᱮᱨᱮᱧ ᱢᱮ',
      'santhali_dev': 'सेरेञ मे',
      'santhali_latin': 'Serenj me',
      'ho': 'दुरंग मे',
      'ho_latin': 'Durang me',
      'mundari': 'दुरंग मे',
      'mundari_latin': 'Durang me',
      'meaning_en': 'Sing a song / rhyme',
    },
    {
      'id': 'cp_smile',
      'intent': 'SMILE',
      'hindi': 'सब बच्चे मुस्कुराओ',
      'keywords_hi': ['मुस्कुराओ', 'हँसो', 'हँसिए'],
      'santhali': 'ᱡᱚᱛᱚ ᱜᱤᱫᱽᱨᱟᱹ ᱞᱟᱸᱫᱟᱭ ᱯᱮ',
      'santhali_dev': 'जोतो गिद्रा लांदाय पे',
      'santhali_latin': 'Joto gidra landay pe',
      'ho': 'सोबेन होनको लांदाए पे',
      'ho_latin': 'Soben honko landae pe',
      'mundari': 'सोबेन हुनको लांदाए पे',
      'mundari_latin': 'Soben hunko landae pe',
      'meaning_en': 'All children smile',
    },
    {
      'id': 'cp_close_book',
      'intent': 'CLOSE_BOOK',
      'hindi': 'किताब बंद करो',
      'keywords_hi': ['किताब बंद करो', 'पुस्तक बंद करो', 'बंद करो'],
      'santhali': 'ᱯᱩᱛᱷᱤ ᱵᱚᱸᱫᱽ ᱢᱮ',
      'santhali_dev': 'पुथि बोंद मे',
      'santhali_latin': 'Puthi bond me',
      'ho': 'पुथि बंद मे',
      'ho_latin': 'Puthi band me',
      'mundari': 'पुथी बंद मे',
      'mundari_latin': 'Puthi band me',
      'meaning_en': 'Close your books',
    },
    {
      'id': 'cp_what_is_this',
      'intent': 'WHAT_IS_THIS',
      'hindi': 'यह क्या है?',
      'keywords_hi': ['यह क्या है', 'ये क्या है', 'क्या है'],
      'santhali': 'ᱱᱚᱣᱟ ᱫᱚ ᱪᱮᱫ ᱠᱟᱱᱟ?',
      'santhali_dev': 'नोवा दो चेद काना?',
      'santhali_latin': 'Nowa do ched kana?',
      'ho': 'नेना चिकना?',
      'ho_latin': 'Nena chikna?',
      'mundari': 'नेना चिकना तना?',
      'mundari_latin': 'Nena chikna tana?',
      'meaning_en': 'What is this?',
    },
    {
      'id': 'cp_understand',
      'intent': 'UNDERSTAND_CHECK',
      'hindi': 'क्या आपको समझ आया?',
      'keywords_hi': ['समझ आया', 'समझ गए', 'समझे'],
      'santhali': 'ᱪᱮᱫ ᱟᱢᱮᱢ ᱵᱩᱡᱷᱟᱹᱣ ᱠᱮᱫᱟ?',
      'santhali_dev': 'चेद आमेम बुझाव केदा?',
      'santhali_latin': 'Ched amem bujhau keda?',
      'ho': 'अम बुझौ केदा?',
      'ho_latin': 'Am bujhau keda?',
      'mundari': 'अम बुझौ केदा?',
      'mundari_latin': 'Am bujhau keda?',
      'meaning_en': 'Did you understand?',
    },
    {
      'id': 'cp_yes_understood',
      'intent': 'YES_UNDERSTOOD',
      'hindi': 'हाँ, समझ गया',
      'keywords_hi': ['समझ गया', 'हाँ समझ गए', 'हाँ सर', 'हाँ मैम'],
      'santhali': 'ᱦᱮᱸ, ᱤᱧᱤᱧ ᱵᱩᱡᱷᱟᱹᱣ ᱠᱮᱫᱟ',
      'santhali_dev': 'हें, इञिञ बुझाव केदा',
      'santhali_latin': 'Hen, inyin bujhau keda',
      'ho': 'हें, अयिंग बुझौ किदा',
      'ho_latin': 'Hen, aying bujhau kida',
      'mundari': 'हें, अयिंग बुझौ किदा',
      'mundari_latin': 'Hen, aying bujhau kida',
      'meaning_en': 'Yes, I understood',
    },
    {
      'id': 'cp_draw_picture',
      'intent': 'DRAW_PICTURE',
      'hindi': 'चित्र बनाओ',
      'keywords_hi': ['चित्र बनाओ', 'फोटो बनाओ', 'ड्राइंग करो'],
      'santhali': 'ᱪᱤᱛᱟᱹᱨ ᱵᱮᱱᱟᱣ ᱢᱮ',
      'santhali_dev': 'चितार बेनाव मे',
      'santhali_latin': 'Chitar benaw me',
      'ho': 'मूरत बनाव मे',
      'ho_latin': 'Murat banaw me',
      'mundari': 'मूरत बनाव मे',
      'mundari_latin': 'Murat banaw me',
      'meaning_en': 'Draw a picture',
    },
    {
      'id': 'cp_tell_name',
      'intent': 'TELL_NAME',
      'hindi': 'अपना नाम बताओ',
      'keywords_hi': ['तुम्हारा नाम क्या है', 'अपना नाम बताओ', 'नाम बताओ'],
      'santhali': 'ᱟᱢᱟᱜ ᱧᱩᱛᱩᱢ ᱞᱟᱹᱭ ᱢᱮ',
      'santhali_dev': 'आमाग ञुतुम लय मे',
      'santhali_latin': 'Amag nyutum lay me',
      'ho': 'अमाः नुतूम काजि मे',
      'ho_latin': 'Amah nutum kaji me',
      'mundari': 'अमाः नुतूम जगर मे',
      'mundari_latin': 'Amah nutum jagar me',
      'meaning_en': 'What is your name? / Tell your name',
    },
    {
      'id': 'cp_dont_run',
      'intent': 'DONT_RUN',
      'hindi': 'दौड़ो मत',
      'keywords_hi': ['दौड़ो मत', 'भागो मत'],
      'santhali': 'ᱟᱞᱚᱢ ᱫᱟᱹᱲᱟ',
      'santhali_dev': 'आलोम दाड़ा',
      'santhali_latin': 'Alom dara',
      'ho': 'का निर मे',
      'ho_latin': 'Ka nir me',
      'mundari': 'का निर मे',
      'mundari_latin': 'Ka nir me',
      'meaning_en': 'Do not run',
    },
    {
      'id': 'cp_eat_food',
      'intent': 'EAT_FOOD',
      'hindi': 'खाना खा लो',
      'keywords_hi': ['खाना खा लो', 'खाना खाओ', 'भोजन करो'],
      'santhali': 'ᱫᱟᱠᱟ ᱡᱚᱢ ᱢᱮ',
      'santhali_dev': 'दाका जोम मे',
      'santhali_latin': 'Daka jom me',
      'ho': 'मंडी जोम मे',
      'ho_latin': 'Mandi jom me',
      'mundari': 'मंडी जोम मे',
      'mundari_latin': 'Mandi jom me',
      'meaning_en': 'Eat your meal',
    },
    {
      'id': 'cp_go_outside',
      'intent': 'GO_OUTSIDE',
      'hindi': 'सभी बच्चे बाहर जाओ',
      'keywords_hi': ['बाहर जाओ', 'सब बच्चे बाहर जाओ', 'सभी बच्चे बाहर जाओ', 'बाहर चले जाओ', 'बाहर चलो', 'बाहर निकलो'],
      'santhali': 'ᱡᱚᱛᱚ ᱜᱤᱫᱽᱨᱟᱹ ᱵᱟᱦᱨᱮ ᱪᱟᱞᱟᱜ ᱯᱮ',
      'santhali_dev': 'जोतो गिद्रा बाहरे चालाग पे',
      'santhali_latin': 'Joto gidra bahre chalag pe',
      'ho': 'सोबेन होनको बाहरे सेन पे',
      'ho_latin': 'Soben honko bahre sen pe',
      'mundari': 'सोबेन हुनको बाहरे सेन पे',
      'mundari_latin': 'Soben hunko bahre sen pe',
      'meaning_en': 'All children go outside',
    },
    {
      'id': 'cp_come_inside',
      'intent': 'COME_INSIDE',
      'hindi': 'सभी बच्चे अंदर आओ',
      'keywords_hi': ['अंदर आओ', 'सब बच्चे अंदर आओ', 'सभी बच्चे अंदर आओ', 'क्लास में आओ', 'कक्षा में आओ', 'अंदर आ जाओ'],
      'santhali': 'ᱡᱚᱛᱚ ᱜᱤᱫᱽᱨᱟᱹ ᱵᱷᱤᱛᱨᱤ ᱦᱤᱡᱩᱜ ᱯᱮ',
      'santhali_dev': 'जोतो गिद्रा भित्री हिजुग पे',
      'santhali_latin': 'Joto gidra bhitri hijug pe',
      'ho': 'सोबेन होनको भितर हिजुः पे',
      'ho_latin': 'Soben honko bhitar hijuh pe',
      'mundari': 'सोबेन हुनको भितर हिजुः पे',
      'mundari_latin': 'Soben hunko bhitar hijuh pe',
      'meaning_en': 'All children come inside',
    },
    {
      'id': 'cp_come_here',
      'intent': 'COME_HERE',
      'hindi': 'यहाँ आओ',
      'keywords_hi': ['यहाँ आओ', 'इधर आओ', 'मेरे पास आओ', 'आगे आओ'],
      'santhali': 'ᱱᱚᱸᱰᱮ ᱦᱤᱡᱩᱜ ᱢᱮ',
      'santhali_dev': 'नोंडे हिजुग मे',
      'santhali_latin': 'Nonde hijug me',
      'ho': 'नेनपा हिजुः मे',
      'ho_latin': 'Nenpa hijuh me',
      'mundari': 'नेते हिजुः मे',
      'mundari_latin': 'Nete hijuh me',
      'meaning_en': 'Come here',
    },
    {
      'id': 'cp_play_ground',
      'intent': 'PLAY_GROUND',
      'hindi': 'मैदान में खेलो',
      'keywords_hi': ['मैदान में खेलो', 'मैदान में जाओ', 'मैदान चलो', 'खेलने जाओ'],
      'santhali': 'ᱴᱟᱺᱰᱤ ᱨᱮ ᱮᱱᱮᱡ ᱯᱮ',
      'santhali_dev': 'तांडी रे एनेज पे',
      'santhali_latin': 'Tandi re enej pe',
      'ho': 'टांडी रे इनुं पे',
      'ho_latin': 'Tandi re inung pe',
      'mundari': 'टांडी रे इनुं पे',
      'mundari_latin': 'Tandi re inung pe',
      'meaning_en': 'Play in the playground',
    },
    {
      'id': 'cp_make_line',
      'intent': 'MAKE_LINE',
      'hindi': 'सब बच्चे लाइन बनाओ',
      'keywords_hi': ['लाइन बनाओ', 'कतार बनाओ', 'सीधे खड़े हो जाओ', 'पंक्ति बनाओ'],
      'santhali': 'ᱡᱚᱛᱚ ᱜᱤᱫᱽᱨᱟᱹ ᱛᱷᱟᱨ ᱵᱮᱱᱟᱣ ᱯᱮ',
      'santhali_dev': 'जोतो गिद्रा थार बेनाव पे',
      'santhali_latin': 'Joto gidra thar benaw pe',
      'ho': 'सोबेन होनको लाइन बनावे पे',
      'ho_latin': 'Soben honko line banawe pe',
      'mundari': 'सोबेन हुनको लाइन बनावे पे',
      'mundari_latin': 'Soben hunko line banawe pe',
      'meaning_en': 'All children make a line',
    },
    {
      'id': 'cp_read_book',
      'intent': 'READ_BOOK',
      'hindi': 'किताब पढ़ो',
      'keywords_hi': ['किताब पढ़ो', 'पाठ पढ़ो', 'किताब पढ़िए'],
      'santhali': 'ᱯᱩᱛᱷᱤ ᱯᱟᱲᱦᱟᱣ ᱢᱮ',
      'santhali_dev': 'पुथि पाढ़ॉव मे',
      'santhali_latin': 'Puthi parhaw me',
      'ho': 'पुथि पड़ाव मे',
      'ho_latin': 'Puthi padaw me',
      'mundari': 'पुथी पड़ाव मे',
      'mundari_latin': 'Puthi padaw me',
      'meaning_en': 'Read the book',
    },
    {
      'id': 'cp_hands_up',
      'intent': 'HANDS_UP',
      'hindi': 'हाथ ऊपर करो',
      'keywords_hi': ['हाथ ऊपर करो', 'हाथ उठाओ', 'हाथ खड़ा करो'],
      'santhali': 'ᱛᱤ ᱪᱮᱛᱟᱱ ᱢᱮ',
      'santhali_dev': 'ती चेतान मे',
      'santhali_latin': 'Ti chetan me',
      'ho': 'ती चेतान मे',
      'ho_latin': 'Ti chetan me',
      'mundari': 'ती चेतान मे',
      'mundari_latin': 'Ti chetan me',
      'meaning_en': 'Raise your hands',
    },
    {
      'id': 'cp_go_home',
      'intent': 'GO_HOME',
      'hindi': 'घर जाओ, छुट्टी हो गई',
      'keywords_hi': ['घर जाओ', 'छुट्टी हो गई', 'घर चले जाओ', 'छुट्टी'],
      'santhali': 'ᱚᱲᱟᱜ ᱪᱟᱞᱟᱜ ᱯᱮ, ᱪᱷᱩᱴᱤ ᱮᱱᱟ',
      'santhali_dev': 'ओड़ाग चालाग पे, छुटी एना',
      'santhali_latin': 'Orag chalag pe, chuti ena',
      'ho': 'ओड़ाः सेन पे, छुटी येना',
      'ho_latin': 'Odah sen pe, chuti yena',
      'mundari': 'ओड़ाः सेन पे, छुटी येना',
      'mundari_latin': 'Odah sen pe, chuti yena',
      'meaning_en': 'Go home, school is over',
    },
  ];

  // -------------------------------------------------------------
  // 2. Cardinal Numbers (PALASH Numeracy FLN 1-100)
  // -------------------------------------------------------------
  static final List<Map<String, dynamic>> numbers = [
    {
      'num': 1,
      'hindi': 'एक',
      'santhali_ol': '᱑',
      'santhali_word': 'ᱢᱤᱫ',
      'santhali_dev': 'मिद',
      'santhali_latin': 'Mid',
      'ho': 'मियद',
      'ho_latin': 'Miyad',
      'mundari': 'मियाद',
      'mundari_latin': 'Miyad',
      'visual': '1️⃣',
    },
    {
      'num': 2,
      'hindi': 'दो',
      'santhali_ol': '᱒',
      'santhali_word': 'ᱵᱟᱨ',
      'santhali_dev': 'बार',
      'santhali_latin': 'Bar',
      'ho': 'बारिया',
      'ho_latin': 'Bariya',
      'mundari': 'बारिया',
      'mundari_latin': 'Bariya',
      'visual': '2️⃣',
    },
    {
      'num': 3,
      'hindi': 'तीन',
      'santhali_ol': '᱓',
      'santhali_word': 'ᱯᱮ',
      'santhali_dev': 'पे',
      'santhali_latin': 'Pe',
      'ho': 'आपिया',
      'ho_latin': 'Apiya',
      'mundari': 'आपिया',
      'mundari_latin': 'Apiya',
      'visual': '3️⃣',
    },
    {
      'num': 4,
      'hindi': 'चार',
      'santhali_ol': '᱔',
      'santhali_word': 'ᱯᱩᱱ',
      'santhali_dev': 'पून',
      'santhali_latin': 'Pun',
      'ho': 'उपुन',
      'ho_latin': 'Upun',
      'mundari': 'उपुन',
      'mundari_latin': 'Upun',
      'visual': '4️⃣',
    },
    {
      'num': 5,
      'hindi': 'पाँच',
      'santhali_ol': '᱕',
      'santhali_word': 'ᱢᱚᱬᱮ',
      'santhali_dev': 'मोणे',
      'santhali_latin': 'Mone',
      'ho': 'मोया',
      'ho_latin': 'Moya',
      'mundari': 'मोड़े',
      'mundari_latin': 'Mode',
      'visual': '5️⃣',
    },
    {
      'num': 6,
      'hindi': 'छह',
      'santhali_ol': '᱖',
      'santhali_word': 'ᱛᱩᱨᱩᱭ',
      'santhali_dev': 'तुरुय',
      'santhali_latin': 'Turuy',
      'ho': 'तुरूया',
      'ho_latin': 'Turuya',
      'mundari': 'तुरूई',
      'mundari_latin': 'Turui',
      'visual': '6️⃣',
    },
    {
      'num': 7,
      'hindi': 'सात',
      'santhali_ol': '᱗',
      'santhali_word': 'ᱮᱭᱟᱭ',
      'santhali_dev': 'एयाय',
      'santhali_latin': 'Eyay',
      'ho': 'ऐया',
      'ho_latin': 'Aiya',
      'mundari': 'एया',
      'mundari_latin': 'Eya',
      'visual': '7️⃣',
    },
    {
      'num': 8,
      'hindi': 'आठ',
      'santhali_ol': '᱘',
      'santhali_word': 'ᱤᱨᱟᱹᱞ',
      'santhali_dev': 'इरल',
      'santhali_latin': 'Iral',
      'ho': 'इरलिया',
      'ho_latin': 'Iraliya',
      'mundari': 'इरिल',
      'mundari_latin': 'Iril',
      'visual': '8️⃣',
    },
    {
      'num': 9,
      'hindi': 'नौ',
      'santhali_ol': '᱙',
      'santhali_word': 'ᱟᱨᱮ',
      'santhali_dev': 'आरे',
      'santhali_latin': 'Are',
      'ho': 'अरेया',
      'ho_latin': 'Areya',
      'mundari': 'आरे',
      'mundari_latin': 'Are',
      'visual': '9️⃣',
    },
    {
      'num': 10,
      'hindi': 'दस',
      'santhali_ol': '᱑᱐',
      'santhali_word': 'ᱜᱮᱞ',
      'santhali_dev': 'गेल',
      'santhali_latin': 'Gel',
      'ho': 'गेल',
      'ho_latin': 'Gel',
      'mundari': 'गेल',
      'mundari_latin': 'Gel',
      'visual': '🔟',
    },
    {
      'num': 20,
      'hindi': 'बीस',
      'santhali_ol': '᱒᱐',
      'santhali_word': 'ᱢᱤᱫ ᱤᱥᱤ',
      'santhali_dev': 'मिद इसी',
      'santhali_latin': 'Mid Isi',
      'ho': 'मियद हीसी',
      'ho_latin': 'Miyad Hisi',
      'mundari': 'मियद हीसी',
      'mundari_latin': 'Miyad Hisi',
      'visual': '🔢',
    },
    {
      'num': 50,
      'hindi': 'पचास',
      'santhali_ol': '᱕᱐',
      'santhali_word': 'ᱵᱟᱨ ᱤᱥᱤ ᱜᱮᱞ',
      'santhali_dev': 'बार इसी गेल',
      'santhali_latin': 'Bar Isi Gel',
      'ho': 'बार हीसी गेल',
      'ho_latin': 'Bar Hisi Gel',
      'mundari': 'बार हीसी गेल',
      'mundari_latin': 'Bar Hisi Gel',
      'visual': '🔢',
    },
    {
      'num': 100,
      'hindi': 'सौ',
      'santhali_ol': '᱑᱐᱐',
      'santhali_word': 'ᱢᱚᱬᱮ ᱤᱥᱤ / ᱥᱟᱭ',
      'santhali_dev': 'मोणे इसी / साय',
      'santhali_latin': 'Mone Isi / Say',
      'ho': 'मोया हीसी / साय',
      'ho_latin': 'Moya Hisi / Say',
      'mundari': 'मोड़े हीसी / साय',
      'mundari_latin': 'Mode Hisi / Say',
      'visual': '💯',
    },
  ];

  // -------------------------------------------------------------
  // 3. Multi-Category Vocabulary (Animals, Nature, Body, School)
  // -------------------------------------------------------------
  static final List<Map<String, dynamic>> vocabulary = [
    // Animals
    {
      'category': 'Animals',
      'hindi': 'बाघ',
      'santhali': 'ᱛᱟᱹᱨᱩᱯ',
      'santhali_dev': 'तारुप',
      'santhali_latin': 'Tarup',
      'ho': 'तुरुप / कुल',
      'ho_latin': 'Kul',
      'mundari': 'कुल',
      'mundari_latin': 'Kul',
      'meaning_en': 'Tiger',
      'visual': '🐯',
    },
    {
      'category': 'Animals',
      'hindi': 'हाथी',
      'santhali': 'ᱦᱟᱹᱛᱤ',
      'santhali_dev': 'हाती',
      'santhali_latin': 'Hati',
      'ho': 'हाती',
      'ho_latin': 'Hati',
      'mundari': 'हाती',
      'mundari_latin': 'Hati',
      'meaning_en': 'Elephant',
      'visual': '🐘',
    },
    {
      'category': 'Animals',
      'hindi': 'चिड़िया',
      'santhali': 'ᱪᱮᱬᱮ',
      'santhali_dev': 'चेणे',
      'santhali_latin': 'Chene',
      'ho': 'चेणो',
      'ho_latin': 'Cheno',
      'mundari': 'चेणो',
      'mundari_latin': 'Cheno',
      'meaning_en': 'Bird',
      'visual': '🐦',
    },
    {
      'category': 'Animals',
      'hindi': 'मछली',
      'santhali': 'ᱦᱟᱹᱠᱩ',
      'santhali_dev': 'हाकु',
      'santhali_latin': 'Haku',
      'ho': 'हाकु',
      'ho_latin': 'Haku',
      'mundari': 'हाकु',
      'mundari_latin': 'Haku',
      'meaning_en': 'Fish',
      'visual': '🐟',
    },
    {
      'category': 'Animals',
      'hindi': 'गाय',
      'santhali': 'ᱜᱟᱹᱭ',
      'santhali_dev': 'गाय',
      'santhali_latin': 'Gay',
      'ho': 'गायी',
      'ho_latin': 'Gayi',
      'mundari': 'ऊरी',
      'mundari_latin': 'Uri',
      'meaning_en': 'Cow',
      'visual': '🐄',
    },

    // Nature & Jharkhand Local Context
    {
      'category': 'Nature',
      'hindi': 'पेड़',
      'santhali': 'ᱫᱟᱨᱮ',
      'santhali_dev': 'दारे',
      'santhali_latin': 'Dare',
      'ho': 'दारे',
      'ho_latin': 'Dare',
      'mundari': 'दारे',
      'mundari_latin': 'Dare',
      'meaning_en': 'Tree',
      'visual': '🌳',
    },
    {
      'category': 'Nature',
      'hindi': 'पत्ता',
      'santhali': 'ᱥᱟᱠᱟᱢ',
      'santhali_dev': 'साकाम',
      'santhali_latin': 'Sakam',
      'ho': 'साकम',
      'ho_latin': 'Sakam',
      'mundari': 'साकम',
      'mundari_latin': 'Sakam',
      'meaning_en': 'Leaf',
      'visual': '🍃',
    },
    {
      'category': 'Nature',
      'hindi': 'फूल (पलाश)',
      'santhali': 'ᱵᱟᱦᱟ (ᱯᱟᱞᱟᱥ)',
      'santhali_dev': 'बाहा (पलाश)',
      'santhali_latin': 'Baha (Palash)',
      'ho': 'बाहा',
      'ho_latin': 'Baha',
      'mundari': 'बा',
      'mundari_latin': 'Ba',
      'meaning_en': 'Flower (Flame of Forest)',
      'visual': '🌺',
    },
    {
      'category': 'Nature',
      'hindi': 'पानी',
      'santhali': 'ᱫᱟᱜ',
      'santhali_dev': 'दाग',
      'santhali_latin': 'Dag',
      'ho': 'दाः',
      'ho_latin': 'Dah',
      'mundari': 'दाः',
      'mundari_latin': 'Dah',
      'meaning_en': 'Water',
      'visual': '💧',
    },
    {
      'category': 'Nature',
      'hindi': 'सूरज',
      'santhali': 'ᱥᱤᱸᱜᱤ',
      'santhali_dev': 'सिंगी',
      'santhali_latin': 'Singi',
      'ho': 'सिंगी',
      'ho_latin': 'Singi',
      'mundari': 'सिंगी',
      'mundari_latin': 'Singi',
      'meaning_en': 'Sun',
      'visual': '☀️',
    },

    // Classroom & Learning
    {
      'category': 'Classroom',
      'hindi': 'किताब / पुस्तक',
      'santhali': 'ᱯᱩᱛᱷᱤ',
      'santhali_dev': 'पुथि',
      'santhali_latin': 'Puthi',
      'ho': 'पुथि',
      'ho_latin': 'Puthi',
      'mundari': 'पुथी',
      'mundari_latin': 'Puthi',
      'meaning_en': 'Book',
      'visual': '📚',
    },
    {
      'category': 'Classroom',
      'hindi': 'कलम / पेन',
      'santhali': 'ᱠᱚᱞᱚᱢ',
      'santhali_dev': 'कोलोम',
      'santhali_latin': 'Kolom',
      'ho': 'कलम',
      'ho_latin': 'Kalam',
      'mundari': 'कलम',
      'mundari_latin': 'Kalam',
      'meaning_en': 'Pen / Pencil',
      'visual': '✏️',
    },
    {
      'category': 'Classroom',
      'hindi': 'शिक्षक / गुरुजी',
      'santhali': 'ᱢᱟᱪᱮᱛ',
      'santhali_dev': 'माचेत',
      'santhali_latin': 'Machet',
      'ho': 'माचेत',
      'ho_latin': 'Machet',
      'mundari': 'माचेत',
      'mundari_latin': 'Machet',
      'meaning_en': 'Teacher',
      'visual': '🧑‍🏫',
    },
    {
      'category': 'Classroom',
      'hindi': 'विद्यार्थी / बच्चे',
      'santhali': 'ᱪᱮᱪᱮᱫᱤᱭᱟᱹ / ᱜᱤᱫᱽᱨᱟᱹ',
      'santhali_dev': 'चेचेदिया / गिद्रा',
      'santhali_latin': 'Chechediya / Gidra',
      'ho': 'होनको',
      'ho_latin': 'Honko',
      'mundari': 'हुनको',
      'mundari_latin': 'Hunko',
      'meaning_en': 'Students / Children',
      'visual': '🧒',
    },
    {
      'category': 'Classroom',
      'hindi': 'विद्यालय / स्कूल',
      'santhali': 'ᱟᱥᱲᱟ',
      'santhali_dev': 'आसड़ा',
      'santhali_latin': 'Asda',
      'ho': 'इस्कुल / आसड़ा',
      'ho_latin': 'Asda',
      'mundari': 'आसड़ा',
      'mundari_latin': 'Asda',
      'meaning_en': 'School',
      'visual': '🏫',
    },

    // Colors
    {
      'category': 'Colors',
      'hindi': 'लाल',
      'santhali': 'ᱟᱨᱟᱜ',
      'santhali_dev': 'आराग',
      'santhali_latin': 'Arag',
      'ho': 'आराः',
      'ho_latin': 'Arah',
      'mundari': 'आराः',
      'mundari_latin': 'Arah',
      'meaning_en': 'Red',
      'visual': '🔴',
    },
    {
      'category': 'Colors',
      'hindi': 'हरा',
      'santhali': 'ᱦᱟᱹᱨᱤᱭᱟᱹᱲ',
      'santhali_dev': 'हारियाड़',
      'santhali_latin': 'Hariyar',
      'ho': 'हरियाड़',
      'ho_latin': 'Hariyar',
      'mundari': 'हरियाड़',
      'mundari_latin': 'Hariyar',
      'meaning_en': 'Green',
      'visual': '🟢',
    },
    {
      'category': 'Colors',
      'hindi': 'सफेद',
      'santhali': 'ᱯᱩᱸᱰ',
      'santhali_dev': 'पुंड',
      'santhali_latin': 'Pund',
      'ho': 'पुंडी',
      'ho_latin': 'Pundi',
      'mundari': 'पुंडी',
      'mundari_latin': 'Pundi',
      'meaning_en': 'White',
      'visual': '⚪',
    },
    {
      'category': 'Colors',
      'hindi': 'काला',
      'santhali': 'ᱦᱮᱸᱫᱮ',
      'santhali_dev': 'हेंदे',
      'santhali_latin': 'Hende',
      'ho': 'हेंदे',
      'ho_latin': 'Hende',
      'mundari': 'हेंदे',
      'mundari_latin': 'Hende',
      'meaning_en': 'Black',
      'visual': '⚫',
    },

    // Shapes
    {
      'category': 'Shapes',
      'hindi': 'गोल / वृत्त',
      'santhali': 'ᱜᱩᱞᱟᱹᱭ',
      'santhali_dev': 'गुलाय',
      'santhali_latin': 'Gulae',
      'ho': 'गोल',
      'ho_latin': 'Gol',
      'mundari': 'गोल',
      'mundari_latin': 'Gol',
      'meaning_en': 'Circle / Round',
      'visual': '⭕',
    },
    {
      'category': 'Shapes',
      'hindi': 'चौकोर / वर्ग',
      'santhali': 'ᱯᱩᱱ ᱠᱳᱬ',
      'santhali_dev': 'पून कोण',
      'santhali_latin': 'Pun Kon',
      'ho': 'उपुन कुट',
      'ho_latin': 'Upun Kut',
      'mundari': 'उपुन कुट',
      'mundari_latin': 'Upun Kut',
      'meaning_en': 'Square / 4-corner',
      'visual': '⬛',
    },
    {
      'category': 'Shapes',
      'hindi': 'त्रिकोण',
      'santhali': 'ᱯᱮ ᱠᱳᱬ',
      'santhali_dev': 'पे कोण',
      'santhali_latin': 'Pe Kon',
      'ho': 'आपिया कुट',
      'ho_latin': 'Apiya Kut',
      'mundari': 'आपिया कुट',
      'mundari_latin': 'Apiya Kut',
      'meaning_en': 'Triangle / 3-corner',
      'visual': '🔺',
    },

    // Food & Nutrition (भोजन एवं फल)
    {
      'category': 'Food',
      'hindi': 'आम',
      'santhali': 'ᱩᱞ',
      'santhali_dev': 'उल',
      'santhali_latin': 'Ul',
      'ho': 'उली',
      'ho_latin': 'Uli',
      'mundari': 'उली',
      'mundari_latin': 'Uli',
      'meaning_en': 'Mango',
      'visual': '🥭',
    },
    {
      'category': 'Food',
      'hindi': 'सेब',
      'santhali': 'ᱥᱮᱣ',
      'santhali_dev': 'सॆव',
      'santhali_latin': 'Sew',
      'ho': 'सेब',
      'ho_latin': 'Seb',
      'mundari': 'सेब',
      'mundari_latin': 'Seb',
      'meaning_en': 'Apple',
      'visual': '🍎',
    },
    {
      'category': 'Food',
      'hindi': 'केला',
      'santhali': 'ᱠᱟᱭᱨᱟ',
      'santhali_dev': 'कायरा',
      'santhali_latin': 'Kayra',
      'ho': 'कदेला',
      'ho_latin': 'Kadela',
      'mundari': 'कदेला',
      'mundari_latin': 'Kadela',
      'meaning_en': 'Banana',
      'visual': '🍌',
    },
    {
      'category': 'Food',
      'hindi': 'फल',
      'santhali': 'ᱡᱚ',
      'santhali_dev': 'जो',
      'santhali_latin': 'Jo',
      'ho': 'जो',
      'ho_latin': 'Jo',
      'mundari': 'जो',
      'mundari_latin': 'Jo',
      'meaning_en': 'Fruit',
      'visual': '🍎',
    },
    {
      'category': 'Food',
      'hindi': 'चावल / भात',
      'santhali': 'ᱫᱟᱠᱟ',
      'santhali_dev': 'दाका',
      'santhali_latin': 'Daka',
      'ho': 'मंडी',
      'ho_latin': 'Mandi',
      'mundari': 'मंडी',
      'mundari_latin': 'Mandi',
      'meaning_en': 'Cooked Rice',
      'visual': '🍚',
    },
    {
      'category': 'Food',
      'hindi': 'दूध',
      'santhali': 'ᱛᱳᱣᱟ',
      'santhali_dev': 'तोवा',
      'santhali_latin': 'Towa',
      'ho': 'तोवा',
      'ho_latin': 'Towa',
      'mundari': 'तोवा',
      'mundari_latin': 'Towa',
      'meaning_en': 'Milk',
      'visual': '🥛',
    },
    {
      'category': 'Food',
      'hindi': 'रोटी',
      'santhali': 'ᱨᱩᱴᱤ',
      'santhali_dev': 'रुटी',
      'santhali_latin': 'Ruti',
      'ho': 'रोटी',
      'ho_latin': 'Roti',
      'mundari': 'रोटी',
      'mundari_latin': 'Roti',
      'meaning_en': 'Bread / Roti',
      'visual': '🫓',
    },

    // Body Parts (शरीर के अंग)
    {
      'category': 'Body',
      'hindi': 'हाथ',
      'santhali': 'ᱛᱤ',
      'santhali_dev': 'ती',
      'santhali_latin': 'Ti',
      'ho': 'ती',
      'ho_latin': 'Ti',
      'mundari': 'ती',
      'mundari_latin': 'Ti',
      'meaning_en': 'Hand',
      'visual': '✋',
    },
    {
      'category': 'Body',
      'hindi': 'आँख',
      'santhali': 'ᱢᱮᱫ',
      'santhali_dev': 'मेद',
      'santhali_latin': 'Med',
      'ho': 'मेद',
      'ho_latin': 'Med',
      'mundari': 'मेद',
      'mundari_latin': 'Med',
      'meaning_en': 'Eye',
      'visual': '👁️',
    },
    {
      'category': 'Body',
      'hindi': 'कान',
      'santhali': 'ᱞᱩᱛᱩᱨ',
      'santhali_dev': 'लुतुर',
      'santhali_latin': 'Lutur',
      'ho': 'लुतुर',
      'ho_latin': 'Lutur',
      'mundari': 'लुतुर',
      'mundari_latin': 'Lutur',
      'meaning_en': 'Ear',
      'visual': '👂',
    },
    {
      'category': 'Body',
      'hindi': 'मुँह',
      'santhali': 'ᱢᱚᱪᱟ',
      'santhali_dev': 'मोचा',
      'santhali_latin': 'Mocha',
      'ho': 'मोचा',
      'ho_latin': 'Mocha',
      'mundari': 'मोचा',
      'mundari_latin': 'Mocha',
      'meaning_en': 'Mouth',
      'visual': '👄',
    },
    {
      'category': 'Body',
      'hindi': 'पैर / पाँव',
      'santhali': 'ᱡᱟᱝᱜᱟ',
      'santhali_dev': 'जांगा',
      'santhali_latin': 'Janga',
      'ho': 'जाता',
      'ho_latin': 'Jata',
      'mundari': 'जांगा',
      'mundari_latin': 'Janga',
      'meaning_en': 'Foot / Leg',
      'visual': '🦶',
    },

    // Family & Relationships (परिवार)
    {
      'category': 'Family',
      'hindi': 'माँ',
      'santhali': 'ᱟᱭᱳ',
      'santhali_dev': 'आयो',
      'santhali_latin': 'Ayo',
      'ho': 'इंगा',
      'ho_latin': 'Inga',
      'mundari': 'इंगा',
      'mundari_latin': 'Inga',
      'meaning_en': 'Mother',
      'visual': '👩',
    },
    {
      'category': 'Family',
      'hindi': 'पिता / पापा',
      'santhali': 'ᱵᱟᱵᱟ',
      'santhali_dev': 'बाबा',
      'santhali_latin': 'Baba',
      'ho': 'आपा',
      'ho_latin': 'Apa',
      'mundari': 'आपा',
      'mundari_latin': 'Apa',
      'meaning_en': 'Father',
      'visual': '👨',
    },
    {
      'category': 'Family',
      'hindi': 'दोस्त / मित्र',
      'santhali': 'ᱜᱟᱛᱮ',
      'santhali_dev': 'गाते',
      'santhali_latin': 'Gate',
      'ho': 'गाते',
      'ho_latin': 'Gate',
      'mundari': 'गाते',
      'mundari_latin': 'Gate',
      'meaning_en': 'Friend',
      'visual': '🤝',
    },
    {
      'category': 'Family',
      'hindi': 'घर',
      'santhali': 'ᱚᱲᱟᱜ',
      'santhali_dev': 'ओड़ाग',
      'santhali_latin': 'Orag',
      'ho': 'ओवाः',
      'ho_latin': 'Owah',
      'mundari': 'ओड़ाः',
      'mundari_latin': 'Odah',
      'meaning_en': 'Home / House',
      'visual': '🏠',
    },
  ];

  // -------------------------------------------------------------
  // 4. Ol Chiki Alphabet (Varnamala with Devanagari Pronunciation)
  // -------------------------------------------------------------
  static final List<Map<String, String>> olChikiAlphabet = [
    {'ol': 'ᱚ', 'dev': 'अ / ल', 'name': 'LA'},
    {'ol': 'ᱛ', 'dev': 'त', 'name': 'AT'},
    {'ol': 'ᱜ', 'dev': 'ग', 'name': 'AG'},
    {'ol': 'ᱝ', 'dev': 'ं (अं)', 'name': 'ANG'},
    {'ol': 'ᱞ', 'dev': 'ल', 'name': 'AL'},
    {'ol': 'ᱟ', 'dev': 'आ', 'name': 'LAA'},
    {'ol': 'ᱠ', 'dev': 'क', 'name': 'AAK'},
    {'ol': 'ᱡ', 'dev': 'ज', 'name': 'AAJ'},
    {'ol': 'ᱢ', 'dev': 'म', 'name': 'AAM'},
    {'ol': 'ᱣ', 'dev': 'व', 'name': 'AAW'},
    {'ol': 'ᱤ', 'dev': 'इ', 'name': 'LI'},
    {'ol': 'ᱥ', 'dev': 'स', 'name': 'IS'},
    {'ol': 'ᱦ', 'dev': 'ह', 'name': 'IH'},
    {'ol': 'ᱧ', 'dev': 'ञ', 'name': 'INY'},
    {'ol': 'ᱨ', 'dev': 'र', 'name': 'IR'},
    {'ol': 'ᱩ', 'dev': 'उ', 'name': 'LU'},
    {'ol': 'ᱪ', 'dev': 'च', 'name': 'UCH'},
    {'ol': 'ᱫ', 'dev': 'द', 'name': 'UD'},
    {'ol': 'ᱬ', 'dev': 'ण', 'name': 'UNN'},
    {'ol': 'ᱭ', 'dev': 'य', 'name': 'UY'},
    {'ol': 'ᱮ', 'dev': 'ए', 'name': 'LE'},
    {'ol': 'ᱯ', 'dev': 'प', 'name': 'EP'},
    {'ol': 'ᱰ', 'dev': 'ड', 'name': 'EDD'},
    {'ol': 'ᱱ', 'dev': 'न', 'name': 'EN'},
    {'ol': 'ᱲ', 'dev': 'ड़', 'name': 'ERR'},
    {'ol': 'ᱳ', 'dev': 'ओ', 'name': 'LO'},
    {'ol': 'ᱴ', 'dev': 'ट', 'name': 'OTT'},
    {'ol': 'ᱵ', 'dev': 'ब', 'name': 'OB'},
    {'ol': 'ᱶ', 'dev': 'ँ (अनुनासिक)', 'name': 'OV'},
    {'ol': 'ᱷ', 'dev': 'ह्', 'name': 'OH'},
  ];

  // -------------------------------------------------------------
  // 5. Dynamic Classroom NLP Dictionary (Words & Multi-Word Chunks)
  // -------------------------------------------------------------
  static final Map<String, Map<String, String>> wordDictionary = {
    // Multi-word chunks
    'सभी बच्चे': {
      'sat': 'ᱡᱚᱛᱚ ᱜᱤᱫᱽᱨᱟᱹ',
      'sat_dev': 'जोतो गिद्रा',
      'sat_lat': 'Joto gidra',
      'ho': 'सोबेन होनको',
      'ho_lat': 'Soben honko',
      'mun': 'सोबेन हुनको',
      'mun_lat': 'Soben hunko',
      'visual': '👥',
      'meaning_en': 'All children',
    },
    'सब बच्चे': {
      'sat': 'ᱡᱚᱛᱚ ᱜᱤᱫᱽᱨᱟᱹ',
      'sat_dev': 'जोतो गिद्रा',
      'sat_lat': 'Joto gidra',
      'ho': 'सोबेन होनको',
      'ho_lat': 'Soben honko',
      'mun': 'सोबेन हुनको',
      'mun_lat': 'Soben hunko',
      'visual': '👥',
      'meaning_en': 'All children',
    },
    'सारे बच्चे': {
      'sat': 'ᱡᱚᱛᱚ ᱜᱤᱫᱽᱨᱟᱹ',
      'sat_dev': 'जोतो गिद्रा',
      'sat_lat': 'Joto gidra',
      'ho': 'सोबेन होनको',
      'ho_lat': 'Soben honko',
      'mun': 'सोबेन हुनको',
      'mun_lat': 'Soben hunko',
      'visual': '👥',
      'meaning_en': 'All children',
    },
    'बाहर जाओ': {
      'sat': 'ᱵᱟᱦᱨᱮ ᱪᱟᱞᱟᱜ ᱯᱮ',
      'sat_dev': 'बाहरे चालाग पे',
      'sat_lat': 'Bahre chalag pe',
      'ho': 'बाहरे सेन पे',
      'ho_lat': 'Bahre sen pe',
      'mun': 'बाहरे सेन पे',
      'mun_lat': 'Bahre sen pe',
      'visual': '🏃‍♂️',
      'meaning_en': 'Go outside',
    },
    'अंदर आओ': {
      'sat': 'ᱵᱷᱤᱛᱨᱤ ᱦᱤᱡᱩᱜ ᱯᱮ',
      'sat_dev': 'भित्री हिजुग पे',
      'sat_lat': 'Bhitri hijug pe',
      'ho': 'भितर हिजुः पे',
      'ho_lat': 'Bhitar hijuh pe',
      'mun': 'भितर हिजुः पे',
      'mun_lat': 'Bhitar hijuh pe',
      'visual': '🏫',
      'meaning_en': 'Come inside',
    },
    'यहाँ आओ': {
      'sat': 'ᱱᱚᱸᱰᱮ ᱦᱤᱡᱩᱜ ᱢᱮ',
      'sat_dev': 'नोंडे हिजुग मे',
      'sat_lat': 'Nonde hijug me',
      'ho': 'नेनपा हिजुः मे',
      'ho_lat': 'Nenpa hijuh me',
      'mun': 'नेते हिजुः मे',
      'mun_lat': 'Nete hijuh me',
      'visual': '👇',
      'meaning_en': 'Come here',
    },
    'वहाँ जाओ': {
      'sat': 'ᱦᱟᱸᱰᱮ ᱪᱟᱞᱟᱜ ᱢᱮ',
      'sat_dev': 'हांडे चालाग मे',
      'sat_lat': 'Hande chalag me',
      'ho': 'एनपा सेन मे',
      'ho_lat': 'Enpa sen me',
      'mun': 'एनते सेन मे',
      'mun_lat': 'Ente sen me',
      'visual': '👉',
      'meaning_en': 'Go there',
    },
    'किताब पढ़ो': {
      'sat': 'ᱯᱩᱛᱷᱤ ᱯᱟᱲᱦᱟᱣ ᱢᱮ',
      'sat_dev': 'पुथि पाढ़ॉव मे',
      'sat_lat': 'Puthi parhaw me',
      'ho': 'पुथि पड़ाव मे',
      'ho_lat': 'Puthi padaw me',
      'mun': 'पुथी पड़ाव मे',
      'mun_lat': 'Puthi padaw me',
      'visual': '📖',
      'meaning_en': 'Read the book',
    },
    'पाठ पढ़ो': {
      'sat': 'ᱯᱟᱲᱦᱟᱣ ᱢᱮ',
      'sat_dev': 'पाढ़ॉव मे',
      'sat_lat': 'Parhaw me',
      'ho': 'पड़ाव मे',
      'ho_lat': 'Padaw me',
      'mun': 'पड़ाव मे',
      'mun_lat': 'Padaw me',
      'visual': '📖',
      'meaning_en': 'Read lesson',
    },
    'कॉपी निकालो': {
      'sat': 'ᱠᱷᱟᱛᱟ ᱚᱰᱚᱠ ᱢᱮ',
      'sat_dev': 'खाता ओडोक मे',
      'sat_lat': 'Khata odok me',
      'ho': 'खाता ओडोः मे',
      'ho_lat': 'Khata odoh me',
      'mun': 'खाता ओडोः मे',
      'mun_lat': 'Khata odoh me',
      'visual': '📝',
      'meaning_en': 'Take out notebook',
    },
    'लाइन बनाओ': {
      'sat': 'ᱛᱷᱟᱨ ᱵᱮᱱᱟᱣ ᱯᱮ',
      'sat_dev': 'थार बेनाव पे',
      'sat_lat': 'Thar benaw pe',
      'ho': 'लाइन बनावे पे',
      'ho_lat': 'Line banawe pe',
      'mun': 'लाइन बनावे पे',
      'mun_lat': 'Line banawe pe',
      'visual': '📏',
      'meaning_en': 'Make a line',
    },
    'हाथ धो लो': {
      'sat': 'ᱛᱤ ᱟᱹᱨᱩᱵ ᱯᱮ',
      'sat_dev': 'ती आरुब पे',
      'sat_lat': 'Ti arub pe',
      'ho': 'ती अरुब पे',
      'ho_lat': 'Ti arub pe',
      'mun': 'ती अरुब पे',
      'mun_lat': 'Ti arub pe',
      'visual': '🧼',
      'meaning_en': 'Wash your hands',
    },
    'पानी पी लो': {
      'sat': 'ᱫᱟᱜ ᱧᱩᱭ ᱯᱮ',
      'sat_dev': 'दाग ञुय पे',
      'sat_lat': 'Dag nyuy pe',
      'ho': 'दाः नुई पे',
      'ho_lat': 'Dah nui pe',
      'mun': 'दाः नुई पे',
      'mun_lat': 'Dah nui pe',
      'visual': '💧',
      'meaning_en': 'Drink water',
    },
    'खाना खा लो': {
      'sat': 'ᱫᱟᱠᱟ ᱡᱚᱢ ᱯᱮ',
      'sat_dev': 'दाका जोम पे',
      'sat_lat': 'Daka jom pe',
      'ho': 'मंडी जोम पे',
      'ho_lat': 'Mandi jom pe',
      'mun': 'मंडी जोम पे',
      'mun_lat': 'Mandi jom me',
      'visual': '🍲',
      'meaning_en': 'Eat your meal',
    },
    'ताली बजाओ': {
      'sat': 'ᱛᱷᱟᱹᱭᱟᱹ ᱯᱮ',
      'sat_dev': 'थाय पे',
      'sat_lat': 'Thaye pe',
      'ho': 'ताली दुर पे',
      'ho_lat': 'Tali dur pe',
      'mun': 'थाली साडी पे',
      'mun_lat': 'Thali sadi pe',
      'visual': '👏',
      'meaning_en': 'Clap hands',
    },
    'बैठ जाओ': {
      'sat': 'ᱫᱩᱲᱩᱵ ᱯᱮ',
      'sat_dev': 'दुड़ुब पे',
      'sat_lat': 'Durup pe',
      'ho': 'दुब पे',
      'ho_lat': 'Dub pe',
      'mun': 'दुब पे',
      'mun_lat': 'Dub pe',
      'visual': '🪑',
      'meaning_en': 'Sit down',
    },
    'खड़े हो जाओ': {
      'sat': 'ᱛᱤᱸᱜᱩᱱ ᱯᱮ',
      'sat_dev': 'तिंगुन पे',
      'sat_lat': 'Tingun pe',
      'ho': 'तिंगुन पे',
      'ho_lat': 'Tingun pe',
      'mun': 'तिंगुन पे',
      'mun_lat': 'Tingun pe',
      'visual': '🧍',
      'meaning_en': 'Stand up',
    },
    'चुप रहो': {
      'sat': 'ᱛᱷᱤᱨ ᱠᱚᱜ ᱯᱮ',
      'sat_dev': 'थीर कोग पे',
      'sat_lat': 'Thir kog pe',
      'ho': 'थीर लेन पे',
      'ho_lat': 'Thir len pe',
      'mun': 'थीर लेन पे',
      'mun_lat': 'Thir len pe',
      'visual': '🤫',
      'meaning_en': 'Be quiet',
    },
    'शांत रहो': {
      'sat': 'ᱛᱷᱤᱨ ᱠᱚᱜ ᱯᱮ',
      'sat_dev': 'थीर कोग पे',
      'sat_lat': 'Thir kog pe',
      'ho': 'थीर लेन पे',
      'ho_lat': 'Thir len pe',
      'mun': 'थीर लेन पे',
      'mun_lat': 'Thir len pe',
      'visual': '🤫',
      'meaning_en': 'Be quiet',
    },
    'मैदान में': {
      'sat': 'ᱴᱟᱺᱰᱤ ᱨᱮ',
      'sat_dev': 'तांडी रे',
      'sat_lat': 'Tandi re',
      'ho': 'टांडी रे',
      'ho_lat': 'Tandi re',
      'mun': 'टांडी रे',
      'mun_lat': 'Tandi re',
      'visual': '🏞️',
      'meaning_en': 'In the playground',
    },
    'कक्षा में': {
      'sat': 'ᱠᱞᱟᱥ ᱨᱮ',
      'sat_dev': 'क्लास रे',
      'sat_lat': 'Class re',
      'ho': 'क्लास रे',
      'ho_lat': 'Class re',
      'mun': 'क्लास रे',
      'mun_lat': 'Class re',
      'visual': '🏫',
      'meaning_en': 'In the classroom',
    },

    // Individual words: Pronouns & Quantifiers
    'सभी': {
      'sat': 'ᱡᱚᱛᱚ',
      'sat_dev': 'जोतो',
      'sat_lat': 'Joto',
      'ho': 'सोबेन',
      'ho_lat': 'Soben',
      'mun': 'सोबेन',
      'mun_lat': 'Soben',
      'visual': '👥',
      'meaning_en': 'All / Everyone',
    },
    'सब': {
      'sat': 'ᱡᱚᱛᱚ',
      'sat_dev': 'जोतो',
      'sat_lat': 'Joto',
      'ho': 'सोबेन',
      'ho_lat': 'Soben',
      'mun': 'सोबेन',
      'mun_lat': 'Soben',
      'visual': '👥',
      'meaning_en': 'All',
    },
    'सारे': {
      'sat': 'ᱡᱚᱛᱚ',
      'sat_dev': 'जोतो',
      'sat_lat': 'Joto',
      'ho': 'सोबेन',
      'ho_lat': 'Soben',
      'mun': 'सोबेन',
      'mun_lat': 'Soben',
      'visual': '👥',
      'meaning_en': 'All',
    },
    'बच्चे': {
      'sat': 'ᱜᱤᱫᱽᱨᱟᱹ',
      'sat_dev': 'गिद्रा',
      'sat_lat': 'Gidra',
      'ho': 'होनको',
      'ho_lat': 'Honko',
      'mun': 'हुनको',
      'mun_lat': 'Hunko',
      'visual': '🧒',
      'meaning_en': 'Children',
    },
    'बच्चों': {
      'sat': 'ᱜᱤᱫᱽᱨᱟᱹ',
      'sat_dev': 'गिद्रा',
      'sat_lat': 'Gidra',
      'ho': 'होनको',
      'ho_lat': 'Honko',
      'mun': 'हुनको',
      'mun_lat': 'Hunko',
      'visual': '🧒',
      'meaning_en': 'Children',
    },
    'बच्चा': {
      'sat': 'ᱜᱤᱫᱽᱨᱟᱹ',
      'sat_dev': 'गिद्रा',
      'sat_lat': 'Gidra',
      'ho': 'होन',
      'ho_lat': 'Hon',
      'mun': 'हुन',
      'mun_lat': 'Hun',
      'visual': '🧒',
      'meaning_en': 'Child',
    },
    'लड़का': {
      'sat': 'ᱠᱚᱲᱟ',
      'sat_dev': 'कोड़ा',
      'sat_lat': 'Koda',
      'ho': 'कोड़ा',
      'ho_lat': 'Koda',
      'mun': 'कोड़ा',
      'mun_lat': 'Koda',
      'visual': '👦',
      'meaning_en': 'Boy',
    },
    'लड़की': {
      'sat': 'ᱠᱩᱲᱤ',
      'sat_dev': 'कुड़ी',
      'sat_lat': 'Kuri',
      'ho': 'कुड़ी',
      'ho_lat': 'Kuri',
      'mun': 'कुड़ी',
      'mun_lat': 'Kuri',
      'visual': '👧',
      'meaning_en': 'Girl',
    },
    'तुम': {
      'sat': 'ᱟᱢ',
      'sat_dev': 'आम',
      'sat_lat': 'Am',
      'ho': 'अम',
      'ho_lat': 'Am',
      'mun': 'अम',
      'mun_lat': 'Am',
      'visual': '👤',
      'meaning_en': 'You',
    },
    'आप': {
      'sat': 'ᱟᱯᱮ',
      'sat_dev': 'आपे',
      'sat_lat': 'Ape',
      'ho': 'अपे',
      'ho_lat': 'Ape',
      'mun': 'अपे',
      'mun_lat': 'Ape',
      'visual': '👤',
      'meaning_en': 'You (plural/respectful)',
    },
    'हम': {
      'sat': 'ᱟᱵᱚ',
      'sat_dev': 'आबो',
      'sat_lat': 'Abo',
      'ho': 'आबू',
      'ho_lat': 'Abu',
      'mun': 'आबू',
      'mun_lat': 'Abu',
      'visual': '👥',
      'meaning_en': 'We',
    },
    'यह': {
      'sat': 'ᱱᱚᱶᱟ',
      'sat_dev': 'नोवा',
      'sat_lat': 'Nowa',
      'ho': 'नेया',
      'ho_lat': 'Neya',
      'mun': 'नेया',
      'mun_lat': 'Neya',
      'visual': '📍',
      'meaning_en': 'This',
    },
    'वह': {
      'sat': 'ᱚᱱᱟ',
      'sat_dev': 'ओना',
      'sat_lat': 'Ona',
      'ho': 'एना',
      'ho_lat': 'Ena',
      'mun': 'एना',
      'mun_lat': 'Ena',
      'visual': '📍',
      'meaning_en': 'That',
    },

    // Directions & Positions
    'बाहर': {
      'sat': 'ᱵᱟᱦᱨᱮ',
      'sat_dev': 'बाहरे',
      'sat_lat': 'Bahre',
      'ho': 'बाहरे',
      'ho_lat': 'Bahre',
      'mun': 'बाहरे',
      'mun_lat': 'Bahre',
      'visual': '🚪',
      'meaning_en': 'Outside',
    },
    'अंदर': {
      'sat': 'ᱵᱷᱤᱛᱨᱤ',
      'sat_dev': 'भित्री',
      'sat_lat': 'Bhitri',
      'ho': 'भितर',
      'ho_lat': 'Bhitar',
      'mun': 'भितर',
      'mun_lat': 'Bhitar',
      'visual': '🏠',
      'meaning_en': 'Inside',
    },
    'यहाँ': {
      'sat': 'ᱱᱚᱸᱰᱮ',
      'sat_dev': 'नोंडे',
      'sat_lat': 'Nonde',
      'ho': 'नेनपा',
      'ho_lat': 'Nenpa',
      'mun': 'नेते',
      'mun_lat': 'Nete',
      'visual': '👇',
      'meaning_en': 'Here',
    },
    'इधर': {
      'sat': 'ᱱᱚᱸᱰᱮ',
      'sat_dev': 'नोंडे',
      'sat_lat': 'Nonde',
      'ho': 'नेनपा',
      'ho_lat': 'Nenpa',
      'mun': 'नेते',
      'mun_lat': 'Nete',
      'visual': '👇',
      'meaning_en': 'Here',
    },
    'वहाँ': {
      'sat': 'ᱦᱟᱸᱰᱮ',
      'sat_dev': 'हांडे',
      'sat_lat': 'Hande',
      'ho': 'एनपा',
      'ho_lat': 'Enpa',
      'mun': 'एनते',
      'mun_lat': 'Ente',
      'visual': '👉',
      'meaning_en': 'There',
    },
    'उधर': {
      'sat': 'ᱦᱟᱸᱰᱮ',
      'sat_dev': 'हांडे',
      'sat_lat': 'Hande',
      'ho': 'एनपा',
      'ho_lat': 'Enpa',
      'mun': 'एनते',
      'mun_lat': 'Ente',
      'visual': '👉',
      'meaning_en': 'There',
    },
    'ऊपर': {
      'sat': 'ᱪᱮᱛᱟᱱ',
      'sat_dev': 'चेतान',
      'sat_lat': 'Chetan',
      'ho': 'चेतान',
      'ho_lat': 'Chetan',
      'mun': 'चेतान',
      'mun_lat': 'Chetan',
      'visual': '⬆️',
      'meaning_en': 'Up / Above',
    },
    'नीचे': {
      'sat': 'ᱞᱟᱛᱟᱨ',
      'sat_dev': 'लातार',
      'sat_lat': 'Latar',
      'ho': 'लातार',
      'ho_lat': 'Latar',
      'mun': 'लातार',
      'mun_lat': 'Latar',
      'visual': '⬇️',
      'meaning_en': 'Down / Below',
    },
    'सामने': {
      'sat': 'ᱢᱟᱲᱟᱝ',
      'sat_dev': 'माड़ांग',
      'sat_lat': 'Marang',
      'ho': 'माड़ांग',
      'ho_lat': 'Marang',
      'mun': 'माड़ांग',
      'mun_lat': 'Marang',
      'visual': '▶️',
      'meaning_en': 'In front',
    },
    'पीछे': {
      'sat': 'ᱛᱟᱭᱚᱢ',
      'sat_dev': 'तायोम',
      'sat_lat': 'Tayom',
      'ho': 'तायोम',
      'ho_lat': 'Tayom',
      'mun': 'तायोम',
      'mun_lat': 'Tayom',
      'visual': '◀️',
      'meaning_en': 'Behind',
    },

    // Verbs & Imperative Actions
    'जाओ': {
      'sat': 'ᱪᱟᱞᱟᱜ ᱯᱮ',
      'sat_dev': 'चालाग पे',
      'sat_lat': 'Chalag pe',
      'ho': 'सेन पे',
      'ho_lat': 'Sen pe',
      'mun': 'सेन पे',
      'mun_lat': 'Sen pe',
      'visual': '🚶',
      'meaning_en': 'Go',
    },
    'जा': {
      'sat': 'ᱪᱟᱞᱟᱜ ᱢᱮ',
      'sat_dev': 'चालाग मे',
      'sat_lat': 'Chalag me',
      'ho': 'सेन मे',
      'ho_lat': 'Sen me',
      'mun': 'सेन मे',
      'mun_lat': 'Sen me',
      'visual': '🚶',
      'meaning_en': 'Go',
    },
    'आओ': {
      'sat': 'ᱦᱤᱡᱩᱜ ᱯᱮ',
      'sat_dev': 'हिजुग पे',
      'sat_lat': 'Hijug pe',
      'ho': 'हिजुः पे',
      'ho_lat': 'Hijuh pe',
      'mun': 'हिजुः पे',
      'mun_lat': 'Hijuh pe',
      'visual': '🏃',
      'meaning_en': 'Come',
    },
    'आ': {
      'sat': 'ᱦᱤᱡᱩᱜ ᱢᱮ',
      'sat_dev': 'हिजुग मे',
      'sat_lat': 'Hijug me',
      'ho': 'हिजुः मे',
      'ho_lat': 'Hijuh me',
      'mun': 'हिजुः मे',
      'mun_lat': 'Hijuh me',
      'visual': '🏃',
      'meaning_en': 'Come',
    },
    'बैठो': {
      'sat': 'ᱫᱩᱲᱩᱵ ᱯᱮ',
      'sat_dev': 'दुड़ुब पे',
      'sat_lat': 'Durup pe',
      'ho': 'दुब पे',
      'ho_lat': 'Dub pe',
      'mun': 'दुब पे',
      'mun_lat': 'Dub pe',
      'visual': '🪑',
      'meaning_en': 'Sit',
    },
    'उठो': {
      'sat': 'ᱛᱤᱸᱜᱩᱱ ᱯᱮ',
      'sat_dev': 'तिंगुन पे',
      'sat_lat': 'Tingun pe',
      'ho': 'तिंगुन पे',
      'ho_lat': 'Tingun pe',
      'mun': 'तिंगुन पे',
      'mun_lat': 'Tingun pe',
      'visual': '🧍',
      'meaning_en': 'Stand up',
    },
    'पढ़ो': {
      'sat': 'ᱯᱟᱲᱦᱟᱣ ᱯᱮ',
      'sat_dev': 'पाढ़ॉव पे',
      'sat_lat': 'Parhaw pe',
      'ho': 'पड़ाव पे',
      'ho_lat': 'Padaw pe',
      'mun': 'पड़ाव पे',
      'mun_lat': 'Padaw pe',
      'visual': '📖',
      'meaning_en': 'Read',
    },
    'लिखो': {
      'sat': 'ᱚᱞ ᱯᱮ',
      'sat_dev': 'ओल पे',
      'sat_lat': 'Ol pe',
      'ho': 'ओल पे',
      'ho_lat': 'Ol pe',
      'mun': 'ओल पे',
      'mun_lat': 'Ol pe',
      'visual': '✏️',
      'meaning_en': 'Write',
    },
    'सुनो': {
      'sat': 'ᱟᱧᱡᱚᱢ ᱯᱮ',
      'sat_dev': 'आंजोम पे',
      'sat_lat': 'Anjom pe',
      'ho': 'आयुम पे',
      'ho_lat': 'Ayum pe',
      'mun': 'आयुम पे',
      'mun_lat': 'Ayum pe',
      'visual': '👂',
      'meaning_en': 'Listen',
    },
    'बोलो': {
      'sat': 'ᱨᱚᱲ ᱯᱮ',
      'sat_dev': 'रोड़ पे',
      'sat_lat': 'Rod pe',
      'ho': 'काजि पे',
      'ho_lat': 'Kaji pe',
      'mun': 'जगर पे',
      'mun_lat': 'Jagar pe',
      'visual': '🗣️',
      'meaning_en': 'Speak',
    },
    'देखो': {
      'sat': 'ᱧᱮᱞ ᱯᱮ',
      'sat_dev': 'ञेल पे',
      'sat_lat': 'Nyel pe',
      'ho': 'नेल पे',
      'ho_lat': 'Nel pe',
      'mun': 'नेल पे',
      'mun_lat': 'Nel pe',
      'visual': '👀',
      'meaning_en': 'Look',
    },
    'खेलो': {
      'sat': 'ᱮᱱᱮᱡ ᱯᱮ',
      'sat_dev': 'एनेज पे',
      'sat_lat': 'Enej pe',
      'ho': 'इनुं पे',
      'ho_lat': 'Inung pe',
      'mun': 'इनुं पे',
      'mun_lat': 'Inung pe',
      'visual': '⚽',
      'meaning_en': 'Play',
    },
    'दौड़ो': {
      'sat': 'ᱫᱟᱹᱲ ᱯᱮ',
      'sat_dev': 'दाड़ पे',
      'sat_lat': 'Dar pe',
      'ho': 'निर पे',
      'ho_lat': 'Nir pe',
      'mun': 'निर पे',
      'mun_lat': 'Nir pe',
      'visual': '🏃',
      'meaning_en': 'Run',
    },
    'खाओ': {
      'sat': 'ᱡᱚᱢ ᱯᱮ',
      'sat_dev': 'जोम पे',
      'sat_lat': 'Jom pe',
      'ho': 'जोम पे',
      'ho_lat': 'Jom pe',
      'mun': 'जोम पे',
      'mun_lat': 'Jom pe',
      'visual': '🍲',
      'meaning_en': 'Eat',
    },
    'पियो': {
      'sat': 'ᱧᱩᱭ ᱯᱮ',
      'sat_dev': 'ञुय पे',
      'sat_lat': 'Nyuy pe',
      'ho': 'नुई पे',
      'ho_lat': 'Nui pe',
      'mun': 'नुई पे',
      'mun_lat': 'Nui pe',
      'visual': '💧',
      'meaning_en': 'Drink',
    },
    'हँसो': {
      'sat': 'ᱞᱟᱸᱫᱟᱭ ᱯᱮ',
      'sat_dev': 'लांदाय पे',
      'sat_lat': 'Landay pe',
      'ho': 'लांदाए पे',
      'ho_lat': 'Landae pe',
      'mun': 'लांदाए पे',
      'mun_lat': 'Landae pe',
      'visual': '😊',
      'meaning_en': 'Smile / Laugh',
    },
    'गाओ': {
      'sat': 'ᱥᱮᱨᱮᱧ ᱯᱮ',
      'sat_dev': 'सेरेञ पे',
      'sat_lat': 'Sereny pe',
      'ho': 'दुरंग पे',
      'ho_lat': 'Durang pe',
      'mun': 'दुरंग पे',
      'mun_lat': 'Durang pe',
      'visual': '🎵',
      'meaning_en': 'Sing',
    },
    'नाचो': {
      'sat': 'ᱮᱱᱮᱡ ᱯᱮ',
      'sat_dev': 'एनेज पे',
      'sat_lat': 'Enej pe',
      'ho': 'सुसुन पे',
      'ho_lat': 'Susun pe',
      'mun': 'सुसुन पे',
      'mun_lat': 'Susun pe',
      'visual': '💃',
      'meaning_en': 'Dance',
    },
    'गिनो': {
      'sat': 'ᱞᱮᱠᱷᱟᱭ ᱯᱮ',
      'sat_dev': 'लेखाय पे',
      'sat_lat': 'Lekhay pe',
      'ho': 'लेकाए पे',
      'ho_lat': 'Lekae pe',
      'mun': 'लेकाए पे',
      'mun_lat': 'Lekae pe',
      'visual': '🔢',
      'meaning_en': 'Count',
    },
    'खोलो': {
      'sat': 'ᱠᱷᱩᱞᱟᱹᱭ ᱯᱮ',
      'sat_dev': 'खुलाय पे',
      'sat_lat': 'Khulay pe',
      'ho': 'कुलै पे',
      'ho_lat': 'Kulae pe',
      'mun': 'कुलै पे',
      'mun_lat': 'Kulae pe',
      'visual': '📂',
      'meaning_en': 'Open',
    },
    'चलो': {
      'sat': 'ᱫᱮᱞᱟ',
      'sat_dev': 'देला',
      'sat_lat': 'Dela',
      'ho': 'दिला',
      'ho_lat': 'Dila',
      'mun': 'दिला',
      'mun_lat': 'Dila',
      'visual': '🚶',
      'meaning_en': 'Come along / Let us go',
    },

    // Classroom & Nature Objects
    'मैदान': {
      'sat': 'ᱴᱟᱺᱰᱤ',
      'sat_dev': 'तांडी',
      'sat_lat': 'Tandi',
      'ho': 'टांडी',
      'ho_lat': 'Tandi',
      'mun': 'टांडी',
      'mun_lat': 'Tandi',
      'visual': '🏞️',
      'meaning_en': 'Playground',
    },
    'स्कूल': {
      'sat': 'ᱟᱥᱲᱟ',
      'sat_dev': 'आसड़ा',
      'sat_lat': 'Asra',
      'ho': 'आसड़ा',
      'ho_lat': 'Asda',
      'mun': 'आसड़ा',
      'mun_lat': 'Asda',
      'visual': '🏫',
      'meaning_en': 'School',
    },
    'घर': {
      'sat': 'ᱚᱲᱟᱜ',
      'sat_dev': 'ओड़ाग',
      'sat_lat': 'Orag',
      'ho': 'ओड़ाः',
      'ho_lat': 'Odah',
      'mun': 'ओड़ाः',
      'mun_lat': 'Odah',
      'visual': '🏠',
      'meaning_en': 'Home',
    },
    'किताब': {
      'sat': 'ᱯᱩᱛᱷᱤ',
      'sat_dev': 'पुथि',
      'sat_lat': 'Puthi',
      'ho': 'पुथि',
      'ho_lat': 'Puthi',
      'mun': 'पुथी',
      'mun_lat': 'Puthi',
      'visual': '📚',
      'meaning_en': 'Book',
    },
    'कॉपी': {
      'sat': 'ᱠᱷᱟᱛᱟ',
      'sat_dev': 'खाता',
      'sat_lat': 'Khata',
      'ho': 'खाता',
      'ho_lat': 'Khata',
      'mun': 'खाता',
      'mun_lat': 'Khata',
      'visual': '📓',
      'meaning_en': 'Notebook',
    },
    'कलम': {
      'sat': 'ᱠᱚᱞᱚᱢ',
      'sat_dev': 'कोलोम',
      'sat_lat': 'Kolom',
      'ho': 'कलम',
      'ho_lat': 'Kalam',
      'mun': 'कलम',
      'mun_lat': 'Kalam',
      'visual': '✏️',
      'meaning_en': 'Pen',
    },
    'हाथ': {
      'sat': 'ᱛᱤ',
      'sat_dev': 'ती',
      'sat_lat': 'Ti',
      'ho': 'ती',
      'ho_lat': 'Ti',
      'mun': 'ती',
      'mun_lat': 'Ti',
      'visual': '✋',
      'meaning_en': 'Hand',
    },
    'पानी': {
      'sat': 'ᱫᱟᱜ',
      'sat_dev': 'दाग',
      'sat_lat': 'Dag',
      'ho': 'दाः',
      'ho_lat': 'Dah',
      'mun': 'दाः',
      'mun_lat': 'Dah',
      'visual': '💧',
      'meaning_en': 'Water',
    },
    'खाना': {
      'sat': 'ᱫᱟᱠᱟ',
      'sat_dev': 'दाका',
      'sat_lat': 'Daka',
      'ho': 'मंडी',
      'ho_lat': 'Mandi',
      'mun': 'मंडी',
      'mun_lat': 'Mandi',
      'visual': '🍲',
      'meaning_en': 'Food',
    },
    'पेड़': {
      'sat': 'ᱫᱟᱨᱮ',
      'sat_dev': 'दारे',
      'sat_lat': 'Dare',
      'ho': 'दारे',
      'ho_lat': 'Dare',
      'mun': 'दारे',
      'mun_lat': 'Dare',
      'visual': '🌳',
      'meaning_en': 'Tree',
    },
    'फूल': {
      'sat': 'ᱵᱟᱦᱟ',
      'sat_dev': 'बाहा',
      'sat_lat': 'Baha',
      'ho': 'बाहा',
      'ho_lat': 'Baha',
      'mun': 'बा',
      'mun_lat': 'Ba',
      'visual': '🌸',
      'meaning_en': 'Flower',
    },
    'पत्ता': {
      'sat': 'ᱥᱟᱠᱟᱢ',
      'sat_dev': 'साकाम',
      'sat_lat': 'Sakam',
      'ho': 'साकम',
      'ho_lat': 'Sakam',
      'mun': 'साकम',
      'mun_lat': 'Sakam',
      'visual': '🍃',
      'meaning_en': 'Leaf',
    },

    // Connectors & Grammar particles
    'और': {
      'sat': 'ᱟᱨ',
      'sat_dev': 'आर',
      'sat_lat': 'Ar',
      'ho': 'आर',
      'ho_lat': 'Ar',
      'mun': 'ओड़ोः',
      'mun_lat': 'Odoh',
      'visual': '➕',
      'meaning_en': 'and',
    },
    'में': {
      'sat': 'ᱨᱮ',
      'sat_dev': 'रे',
      'sat_lat': 'Re',
      'ho': 'रे',
      'ho_lat': 'Re',
      'mun': 'रे',
      'mun_lat': 'Re',
      'visual': '📍',
      'meaning_en': 'in',
    },
    'से': {
      'sat': 'ᱠᱷᱚᱱ',
      'sat_dev': 'खोन',
      'sat_lat': 'Khon',
      'ho': 'एते',
      'ho_lat': 'Ete',
      'mun': 'एते',
      'mun_lat': 'Ete',
      'visual': '➡️',
      'meaning_en': 'from',
    },
    'को': {
      'sat': 'ᱛᱮ',
      'sat_dev': 'ते',
      'sat_lat': 'Te',
      'ho': 'ते',
      'ho_lat': 'Te',
      'mun': 'ते',
      'mun_lat': 'Te',
      'visual': '🎯',
      'meaning_en': 'to',
    },
    'पर': {
      'sat': 'ᱨᱮ',
      'sat_dev': 'रे',
      'sat_lat': 'Re',
      'ho': 'रे',
      'ho_lat': 'Re',
      'mun': 'रे',
      'mun_lat': 'Re',
      'visual': '🔝',
      'meaning_en': 'on',
    },
    'मत': {
      'sat': 'ᱟᱞᱚ',
      'sat_dev': 'आलो',
      'sat_lat': 'Alo',
      'ho': 'का',
      'ho_lat': 'Ka',
      'mun': 'का',
      'mun_lat': 'Ka',
      'visual': '🚫',
      'meaning_en': 'do not',
    },
    'नहीं': {
      'sat': 'ᱵᱟᱝ',
      'sat_dev': 'बांग',
      'sat_lat': 'Bang',
      'ho': 'का',
      'ho_lat': 'Ka',
      'mun': 'का',
      'mun_lat': 'Ka',
      'visual': '❌',
      'meaning_en': 'no / not',
    },
    'हाँ': {
      'sat': 'ᱦᱮᱸ',
      'sat_dev': 'हें',
      'sat_lat': 'Hen',
      'ho': 'हें',
      'ho_lat': 'Hen',
      'mun': 'हें',
      'mun_lat': 'Hen',
      'visual': '✅',
      'meaning_en': 'yes',
    },
  };

  // -------------------------------------------------------------
  // 6. Universal English & Hinglish Classroom Intent Map
  // -------------------------------------------------------------
  static final Map<String, String> englishHinglishToIntent = {
    // Open Book
    'open your book': 'OPEN_BOOK',
    'open book': 'OPEN_BOOK',
    'open books': 'OPEN_BOOK',
    'kitab kholo': 'OPEN_BOOK',
    'apni kitab kholo': 'OPEN_BOOK',
    'pustak kholo': 'OPEN_BOOK',
    'apni pustak kholo': 'OPEN_BOOK',
    'book open karo': 'OPEN_BOOK',
    'kitab open karo': 'OPEN_BOOK',

    // Sit Down
    'sit down': 'SIT_DOWN',
    'sit': 'SIT_DOWN',
    'please sit down': 'SIT_DOWN',
    'baith jao': 'SIT_DOWN',
    'sab baith jao': 'SIT_DOWN',
    'sab bache baith jao': 'SIT_DOWN',
    'baitho': 'SIT_DOWN',
    'apni jagah baitho': 'SIT_DOWN',

    // Stand Up
    'stand up': 'STAND_UP',
    'stand': 'STAND_UP',
    'khade ho jao': 'STAND_UP',
    'khade ho': 'STAND_UP',
    'sab khade ho jao': 'STAND_UP',
    'utho': 'STAND_UP',

    // Look Here
    'look here': 'LOOK_HERE',
    'look at the board': 'LOOK_HERE',
    'look': 'LOOK_HERE',
    'yahan dekho': 'LOOK_HERE',
    'idhar dekho': 'LOOK_HERE',
    'board par dekho': 'LOOK_HERE',
    'board pe dekho': 'LOOK_HERE',

    // Listen Carefully
    'listen': 'LISTEN',
    'listen carefully': 'LISTEN',
    'listen to me': 'LISTEN',
    'dhyan se suno': 'LISTEN',
    'suno': 'LISTEN',
    'meri baat suno': 'LISTEN',
    'sab suno': 'LISTEN',

    // Repeat After Me
    'repeat': 'REPEAT',
    'repeat after me': 'REPEAT',
    'say after me': 'REPEAT',
    'dohrao': 'REPEAT',
    'mere baad bolo': 'REPEAT',
    'peeche bolo': 'REPEAT',
    'mere piche bolo': 'REPEAT',

    // Greetings
    'hello': 'GREETING',
    'hi': 'GREETING',
    'good morning': 'GREETING',
    'greetings': 'GREETING',
    'namaste': 'GREETING',
    'pranam': 'GREETING',
    'namaskar': 'GREETING',
    'suprabhat': 'GREETING',
    'johar': 'GREETING',

    // How Are You
    'how are you': 'HOW_ARE_YOU',
    'how are you all': 'HOW_ARE_YOU',
    'kaise ho': 'HOW_ARE_YOU',
    'aap kaise ho': 'HOW_ARE_YOU',
    'kaisa hai': 'HOW_ARE_YOU',
    'sab theek': 'HOW_ARE_YOU',

    // We Are Fine
    'we are fine': 'WE_ARE_FINE',
    'we are good': 'WE_ARE_FINE',
    'i am fine': 'WE_ARE_FINE',
    'hum theek hain': 'WE_ARE_FINE',
    'hum ache hain': 'WE_ARE_FINE',
    'badiya hain': 'WE_ARE_FINE',
    'sab theek hai': 'WE_ARE_FINE',

    // Drink Water
    'drink water': 'DRINK_WATER',
    'drink': 'DRINK_WATER',
    'water': 'DRINK_WATER',
    'pani piyo': 'DRINK_WATER',
    'paani piyo': 'DRINK_WATER',
    'pani pina hai': 'DRINK_WATER',
    'paani pina hai': 'DRINK_WATER',

    // Wash Hands
    'wash hands': 'WASH_HANDS',
    'wash your hands': 'WASH_HANDS',
    'hand wash': 'WASH_HANDS',
    'haath dhoo lo': 'WASH_HANDS',
    'hath dhoo': 'WASH_HANDS',
    'haath saaf karo': 'WASH_HANDS',

    // Midday Meal / Eat Food
    'eat food': 'MIDDAY_MEAL',
    'eat your meal': 'MIDDAY_MEAL',
    'eat lunch': 'MIDDAY_MEAL',
    'mid day meal': 'MIDDAY_MEAL',
    'khana khao': 'MIDDAY_MEAL',
    'bhojan karo': 'MIDDAY_MEAL',
    'khana khalo': 'MIDDAY_MEAL',

    // Clap Hands
    'clap': 'CLAP',
    'clap your hands': 'CLAP',
    'clapping': 'CLAP',
    'tali bajao': 'CLAP',
    'tali maro': 'CLAP',

    // Write on Slate / Copy
    'write': 'WRITE',
    'write on your slate': 'WRITE',
    'write down': 'WRITE',
    'likho': 'WRITE',
    'slate par likho': 'WRITE',
    'copy me likho': 'WRITE',

    // Come Here
    'come here': 'COME_HERE',
    'come': 'COME_HERE',
    'yahan aao': 'COME_HERE',
    'idhar aao': 'COME_HERE',

    // Go Outside
    'go outside': 'GO_OUTSIDE',
    'go out': 'GO_OUTSIDE',
    'bahar jao': 'GO_OUTSIDE',
    'bahar chalo': 'GO_OUTSIDE',

    // Be Quiet / Silence
    'be quiet': 'BE_QUIET',
    'keep quiet': 'BE_QUIET',
    'silence': 'BE_QUIET',
    'quiet': 'BE_QUIET',
    'shant raho': 'BE_QUIET',
    'chup raho': 'BE_QUIET',
    'chup': 'BE_QUIET',

    // Good Job / Praise
    'good job': 'GOOD',
    'very good': 'GOOD',
    'well done': 'GOOD',
    'excellent': 'GOOD',
    'bahut achha': 'GOOD',
    'bahut badhiya': 'GOOD',
    'shabash': 'GOOD',

    // Try Again
    'try again': 'TRY_AGAIN',
    'phir se koshish karo': 'TRY_AGAIN',
    'dobara karo': 'TRY_AGAIN',

    // Count Together
    'count': 'COUNT',
    'count together': 'COUNT',
    'gino': 'COUNT',
    'ginti karo': 'COUNT',

    // Go Home
    'go home': 'GO_HOME',
    'school is over': 'GO_HOME',
    'ghar jao': 'GO_HOME',
    'chutti ho gayi': 'GO_HOME',
    'chhutti': 'GO_HOME',
  };

  // -------------------------------------------------------------
  // 7. Universal English & Hinglish Vocabulary Noun/Verb Map
  // -------------------------------------------------------------
  static final Map<String, String> englishHinglishToHindiVocab = {
    // Fruits & Food
    'apple': 'सेब', 'seb': 'सेब',
    'mango': 'आम', 'aam': 'आम',
    'banana': 'केला', 'kela': 'केला',
    'guava': 'अमरूद', 'amrud': 'अमरूद',
    'rice': 'चावल / भात', 'chawal': 'चावल / भात', 'bhat': 'चावल / भात',
    'roti': 'रोटी', 'bread': 'रोटी',
    'milk': 'दूध', 'dudh': 'दूध', 'doodh': 'दूध',
    'water': 'पानी', 'pani': 'पानी', 'paani': 'पानी',

    // Animals & Birds
    'elephant': 'हाथी', 'hathi': 'हाथी', 'haathi': 'हाथी',
    'cow': 'गाय', 'gay': 'गाय', 'gai': 'गाय',
    'goat': 'बकरी', 'bakri': 'बकरी',
    'tiger': 'बाघ', 'bagh': 'बाघ', 'sher': 'बाघ',
    'lion': 'शेर',
    'dog': 'कुत्ता', 'kutta': 'कुत्ता',
    'cat': 'बिल्ली', 'billi': 'बिल्ली',
    'bird': 'चिड़िया / पक्षी', 'chidiya': 'चिड़िया / पक्षी',
    'monkey': 'बंदर', 'bandar': 'बंदर',
    'fish': 'मछली', 'machli': 'मछली',
    'horse': 'घोड़ा', 'ghoda': 'घोड़ा',

    // Nature & Environment
    'tree': 'पेड़', 'ped': 'पेड़', 'per': 'पेड़',
    'flower': 'फूल', 'phool': 'फूल',
    'leaf': 'पत्ता', 'patta': 'पत्ता', 'patte': 'पत्ता',
    'sun': 'सूरज', 'suraj': 'सूरज',
    'moon': 'चाँद', 'chand': 'चाँद', 'chanda': 'चाँद',
    'star': 'तारा', 'tara': 'तारा',
    'river': 'नदी', 'nadi': 'नदी',
    'mountain': 'पहाड़', 'pahad': 'पहाड़',
    'forest': 'जंगल / वन', 'jungle': 'जंगल / वन',

    // Family
    'mother': 'माँ', 'mom': 'माँ', 'maa': 'माँ', 'mata': 'माँ', 'mummy': 'माँ',
    'father': 'पिताजी', 'dad': 'पिताजी', 'papa': 'पिताजी', 'pitaji': 'पिताजी', 'baap': 'पिताजी',
    'brother': 'भाई', 'bhai': 'भाई',
    'sister': 'बहन', 'behan': 'बहन', 'didi': 'बहन',
    'child': 'बच्चा', 'children': 'बच्चे', 'bachha': 'बच्चा', 'bache': 'बच्चे', 'kids': 'बच्चे',
    'teacher': 'शिक्षक', 'guruji': 'शिक्षक', 'sir': 'शिक्षक', 'madam': 'शिक्षक',
    'friend': 'दोस्त / मित्र', 'dost': 'दोस्त / मित्र',

    // Objects & School
    'book': 'किताब / पुस्तक', 'books': 'किताब / पुस्तक', 'kitab': 'किताब / पुस्तक', 'pustak': 'किताब / पुस्तक',
    'pen': 'कलम / पेन', 'kalam': 'कलम / पेन',
    'pencil': 'पेंसिल',
    'slate': 'स्लेट',
    'school': 'विद्यालय / स्कूल',
    'home': 'घर', 'house': 'घर', 'ghar': 'घर',

    // Colors
    'red': 'लाल', 'lal': 'लाल',
    'green': 'हरा', 'hara': 'हरा',
    'white': 'सफेद', 'safed': 'सफेद',
    'black': 'काला', 'kala': 'काला',
    'blue': 'नीला', 'neela': 'नीला',
    'yellow': 'पीला', 'peela': 'पीला',

    // Shapes
    'circle': 'गोल / वृत्त', 'round': 'गोल / वृत्त', 'gol': 'गोल / वृत्त',
    'square': 'चौकोर / वर्ग', 'choukor': 'चौकोर / वर्ग',
    'triangle': 'त्रिकोण', 'trikon': 'त्रिकोण',
  };
}

